baseURL = "http://example.org/"
languageCode = "en-us"
title = "RapidF5"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowFooter = true
  hideFooter = true

  [params.homeInfoParams]
    Title = "Hey, I'm Cory (RapidF5) 👋"
    Content = "Refreshing thoughts on tech, games, and whatever I’m hyperfixating on this week."



[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2

  [taxonomies]
  tag = "tags"
  category = "categories"

